import { useMemo } from 'react'
import { Button } from '@/shared/components/ui/Button'
import { downloadFile } from '@/shared/lib/download-file'
import { cn } from '@/shared/lib/cn'
import type { FilePreviewItem, FilePreviewModalProps } from '@/shared/types'

export type { FilePreviewItem, FilePreviewModalProps }


function kindFromMime(name: string, mime?: string): 'image' | 'pdf' | 'text' | 'other' {
  const m = (mime ?? '').toLowerCase()
  const n = name.toLowerCase()
  if (m.startsWith('image/') || /\.(png|jpe?g|gif|webp|svg|bmp)$/i.test(n)) return 'image'
  if (m === 'application/pdf' || n.endsWith('.pdf')) return 'pdf'
  if (
    m.startsWith('text/') ||
    m.includes('json') ||
    /\.(txt|md|csv|json|log)$/i.test(n)
  )
    return 'text'
  return 'other'
}

/**
 * Shared document / image preview panel.
 * Layout: header (meta) · mid (viewer) · footer (download).
 * Supports images, PDF (iframe), text, and a fallback for office docs.
 */
export function FilePreviewModal({ open, file, onClose, className }: FilePreviewModalProps) {
  const kind = useMemo(
    () => (file ? kindFromMime(file.name, file.mimeType) : 'other'),
    [file],
  )

  if (!open || !file) return null

  const handleDownload = () => {
    if (file.blob) {
      downloadFile({ blob: file.blob, filename: file.name })
      return
    }
    if (file.url) {
      const a = document.createElement('a')
      a.href = file.url
      a.download = file.name
      a.rel = 'noopener'
      a.target = '_blank'
      document.body.appendChild(a)
      a.click()
      a.remove()
      return
    }
    // Mock placeholder download
    const blob = new Blob(
      [`Preview placeholder for ${file.name}\nGenerated by Bytevon.`],
      { type: 'text/plain' },
    )
    downloadFile({ blob, filename: file.name.replace(/\.[^.]+$/, '') + '.txt' })
  }

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
      <button
        type="button"
        className="absolute inset-0 bg-on-surface/40 backdrop-blur-sm"
        aria-label="Close preview"
        onClick={onClose}
      />
      <div
        role="dialog"
        aria-modal
        aria-label={`Preview ${file.name}`}
        className={cn(
          'relative z-10 w-full max-w-3xl max-h-[90vh] flex flex-col',
          'bg-surface-container-lowest rounded-xl border border-outline-variant executive-shadow',
          className,
        )}
      >
        {/* Header — meta */}
        <div className="px-5 py-4 border-b border-outline-variant flex items-start justify-between gap-3 shrink-0">
          <div className="min-w-0">
            <h3 className="text-title-md font-semibold text-on-background truncate">{file.name}</h3>
            <p className="text-label-sm text-on-surface-variant mt-1 flex flex-wrap gap-x-3 gap-y-1">
              {file.mimeType && <span>{file.mimeType}</span>}
              {file.sizeLabel && <span>{file.sizeLabel}</span>}
              {file.uploadedBy && <span>By {file.uploadedBy}</span>}
              {file.uploadedAt && <span>{file.uploadedAt}</span>}
            </p>
          </div>
          <button
            type="button"
            className="p-2 rounded-full hover:bg-surface-container text-on-surface-variant transition-colors"
            onClick={onClose}
            aria-label="Close"
          >
            <span className="material-symbols-outlined">close</span>
          </button>
        </div>

        {/* Mid — viewer */}
        <div className="flex-1 min-h-[280px] max-h-[55vh] overflow-auto bg-surface-container-low/40 flex items-center justify-center p-4">
          {kind === 'image' && file.url ? (
            <img
              src={file.url}
              alt={file.name}
              className="max-w-full max-h-[50vh] object-contain rounded-lg shadow-sm"
            />
          ) : kind === 'pdf' && file.url ? (
            <iframe
              title={file.name}
              src={file.url}
              className="w-full h-[50vh] rounded-lg border border-outline-variant bg-white"
            />
          ) : kind === 'text' && file.url ? (
            <iframe
              title={file.name}
              src={file.url}
              className="w-full h-[50vh] rounded-lg border border-outline-variant bg-white"
            />
          ) : (
            <div className="text-center space-y-3 py-12 px-6">
              <span className="material-symbols-outlined text-5xl text-on-surface-variant">
                {kind === 'pdf' ? 'picture_as_pdf' : 'description'}
              </span>
              <p className="text-body-md text-on-surface font-medium">{file.name}</p>
              <p className="text-body-sm text-on-surface-variant max-w-sm mx-auto">
                Inline preview is not available for this format. Use Download to open it in your
                system viewer.
              </p>
            </div>
          )}
        </div>

        {/* Footer — download */}
        <div className="px-5 py-4 border-t border-outline-variant flex justify-end gap-2 shrink-0">
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
          <Button
            variant="primary"
            leftIcon={<span className="material-symbols-outlined text-[18px]">download</span>}
            onClick={handleDownload}
          >
            Download
          </Button>
        </div>
      </div>
    </div>
  )
}
