/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Mapped to CSS variables from tokens.css
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-background': 'var(--color-on-background)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        'error-container': 'var(--color-error-container)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'deep-navy': 'var(--color-deep-navy)',
        'electric-blue': 'var(--color-electric-blue)',
        'sidebar-accent': 'var(--color-sidebar-accent)',
        'sidebar-item-active': 'var(--color-sidebar-item-active)',
        'surface-sidebar': 'var(--color-surface-sidebar)',
        'inverse-primary': 'var(--color-inverse-primary)',
        // Status
        'success-emerald': 'var(--color-success-emerald)',
        'on-success': 'var(--color-on-success)',
        'success-container': 'var(--color-success-container)',
        'warning-amber': 'var(--color-warning-amber)',
        'on-warning': 'var(--color-on-warning)',
        'warning-container': 'var(--color-warning-container)',
        // Overlay primitives (prefer component classes; available if needed)
        scrim: 'var(--color-scrim)',
        shadow: 'var(--color-shadow)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius-sm)',
        lg: 'var(--radius-md)',
        xl: 'var(--radius-lg)',
        full: 'var(--radius-full)',
      },
      spacing: {
        'margin-mobile': 'var(--spacing-margin-mobile)',
        'margin-desktop': 'var(--spacing-margin-desktop)',
        gutter: 'var(--spacing-gutter)',
        'nav-gap': 'var(--spacing-unit)',
        'section-gap': 'var(--spacing-section)',
        unit: 'var(--spacing-unit)',
        'sidebar-rail': 'var(--sidebar-rail-width-collapsed)',
        'sidebar-secondary': 'var(--sidebar-secondary-width-expanded)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'nav-item': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'nav-group': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      width: {
        'sidebar-rail': 'var(--sidebar-rail-width-collapsed)',
        'sidebar-rail-expanded': 'var(--sidebar-rail-width-expanded)',
        'sidebar-secondary': 'var(--sidebar-secondary-width-expanded)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        sidebar: 'var(--duration-sidebar)',
      },
      transitionTimingFunction: {
        standard: 'var(--easing-standard)',
        emphasized: 'var(--easing-emphasized)',
      },
    },
  },
  plugins: [],
}
