from app.modules.notes_documents.schemas.schemas import (
    DocumentCreate,
    DocumentDetailResponse,
    DocumentLinkCreate,
    DocumentLinkResponse,
    DocumentResponse,
    DocumentTypeCreate,
    DocumentTypeResponse,
    DocumentTypeUpdate,
    DocumentVersionCreate,
    DocumentVersionResponse,
    MessageResponse,
    NoteCreate,
    NoteResponse,
    NoteUpdate,
)

__all__ = [
    "MessageResponse",
    "NoteCreate",
    "NoteUpdate",
    "NoteResponse",
    "DocumentTypeCreate",
    "DocumentTypeUpdate",
    "DocumentTypeResponse",
    "DocumentCreate",
    "DocumentVersionCreate",
    "DocumentVersionResponse",
    "DocumentResponse",
    "DocumentDetailResponse",
    "DocumentLinkCreate",
    "DocumentLinkResponse",
]
