/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Mapped to CSS variables from tokens.css
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-background': 'var(--color-on-background)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'deep-navy': 'var(--color-deep-navy)',
        'electric-blue': 'var(--color-electric-blue)',
        'sidebar-accent': 'var(--color-sidebar-accent)',
        'sidebar-item-active': 'var(--color-sidebar-item-active)',
        'surface-sidebar': 'var(--color-surface-sidebar)',
        'inverse-primary': 'var(--color-inverse-primary)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        gutter: '24px',
        'nav-gap': '4px',
        'section-gap': '32px',
        unit: '4px',
        'sidebar-rail': '80px',
        'sidebar-secondary': '240px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'nav-item': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'nav-group': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      width: {
        'sidebar-rail': 'var(--sidebar-rail-width-collapsed)',
        'sidebar-rail-expanded': 'var(--sidebar-rail-width-expanded)',
        'sidebar-secondary': 'var(--sidebar-secondary-width-expanded)',
      },
    },
  },
  plugins: [],
}