/** @deprecated Prefer domain folders: pages/location, pages/shift, etc. */
export { LocationsListPage } from '../location/LocationsListPage'
export { LocationDetailPage } from '../location/LocationDetailPage'
export { ShiftsListPage } from '../shift/ShiftsListPage'
export { ShiftDetailPage } from '../shift/ShiftDetailPage'
export { WorkingWeeksPage } from '../working_week/WorkingWeeksPage'
export { HolidayCalendarsPage } from '../holiday_calendar/HolidayCalendarsPage'
export { HolidaysListPage } from '../holiday_calendar/HolidaysListPage'
export { PositionsListPage } from '../position/PositionsListPage'
export { OrganizationSettingsPage } from '../settings/OrganizationSettingsPage'
