"""initial_schema

Revision ID: 4228221ecb21
Revises: 
Create Date: 2026-09-05 13:58:02.509764
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4228221ecb21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_policies',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('correction_window_days', sa.Integer(), nullable=False),
    sa.Column('max_corrections_per_month', sa.Integer(), nullable=True),
    sa.Column('reasons_mandatory', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('approval_sla_hours', sa.Integer(), nullable=True),
    sa.Column('allow_multiple_punches', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('require_checkout_before_new_checkin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_create_attendance_day', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('default_grace_late_minutes', sa.Integer(), nullable=True),
    sa.Column('max_clock_drift_seconds', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Date from which this version becomes effective'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Date until which this version is effective (NULL = current)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_policies'))
    )
    op.create_table('audit_logs',
    sa.Column('reference_type', sa.Enum('EMPLOYMENT', 'LOGIN', 'ROLE', 'PERMISSION', 'DEPARTMENT', 'LOCATION', 'LEAVE_REQUEST', 'ATTENDANCE', 'ATTENDANCE_CORRECTION', 'APPROVAL_REQUEST', 'CLIENT', 'LEAD', 'PROJECT', 'TASK', 'TEAM', 'NOTE', 'DOCUMENT', 'NOTIFICATION', 'ORGANIZATION', 'SYSTEM', 'SESSION', 'PLATFORM', 'PAYROLL', name='auditreferencetype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'ARCHIVE', 'RESTORE', 'LOGIN', 'LOGOUT', 'PASSWORD_CHANGE', 'APPROVE', 'REJECT', 'ASSIGN', 'UNASSIGN', 'STATUS_CHANGE', 'EXPORT', name='auditaction'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_employment_id'), 'audit_logs', ['employment_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_reference_id'), 'audit_logs', ['reference_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_reference_type'), 'audit_logs', ['reference_type'], unique=False)
    op.create_table('clients',
    sa.Column('client_type', sa.Enum('INDIVIDUAL', 'COMPANY', name='clienttype'), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether this record has been archived'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Archive timestamp'),
    sa.Column('archived_by', sa.Integer(), nullable=True, comment='Employment ID who archived this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID who last changed this record (or SYSTEM_EMPLOYMENT_ID)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department_head_employment_id', sa.Integer(), nullable=True, comment='FK employments.id (soft reference)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='Employment ID or SYSTEM_EMPLOYMENT_ID'),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether this record has been archived'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Archive timestamp'),
    sa.Column('archived_by', sa.Integer(), nullable=True, comment='Employment ID who archived this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_table('document_types',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether this record has been archived'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Archive timestamp'),
    sa.Column('archived_by', sa.Integer(), nullable=True, comment='Employment ID who archived this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types'))
    )
    op.create_table('holiday_calendars',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether this record has been archived'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Archive timestamp'),
    sa.Column('archived_by', sa.Integer(), nullable=True, comment='Employment ID who archived this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID who last changed this record (or SYSTEM_EMPLOYMENT_ID)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday_calendars'))
    )
    op.create_table('leave_policies',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'PATERNITY', 'LOSS_OF_PAY', 'COMP_OFF', name='leavetype'), nullable=False),
    sa.Column('annual_entitlement', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carry_forward_limit', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Date from which this version becomes effective'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Date until which this version is effective (NULL = current)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_policies'))
    )
    op.create_index(op.f('ix_leave_policies_leave_type'), 'leave_policies', ['leave_type'], unique=False)
    op.create_table('notes',
    sa.Column('reference_type', sa.Enum('LEAD', 'TASK', 'CLIENT', name='notereferencetype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_reference_id'), 'notes', ['reference_id'], unique=False)
    op.create_index(op.f('ix_notes_reference_type'), 'notes', ['reference_type'], unique=False)
    op.create_table('notification_templates',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title_template', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates')),
    sa.UniqueConstraint('code', name='uq_notification_templates_code')
    )
    op.create_table('persons',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('personal_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_anonymized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_table('platforms',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether this record has been archived'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Archive timestamp'),
    sa.Column('archived_by', sa.Integer(), nullable=True, comment='Employment ID who archived this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID who last changed this record (or SYSTEM_EMPLOYMENT_ID)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms'))
    )
    op.create_table('positions',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether this record has been archived'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Archive timestamp'),
    sa.Column('archived_by', sa.Integer(), nullable=True, comment='Employment ID who archived this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_table('resources',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('name', name=op.f('uq_resources_name'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_table('scopes',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scopes')),
    sa.UniqueConstraint('name', name=op.f('uq_scopes_name'))
    )
    op.create_table('shifts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_overnight', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('grace_late_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('flexible_end', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether this record has been archived'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Archive timestamp'),
    sa.Column('archived_by', sa.Integer(), nullable=True, comment='Employment ID who archived this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID who last changed this record (or SYSTEM_EMPLOYMENT_ID)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_table('working_weeks',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('working_days_of_week', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Date from which this version becomes effective'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Date until which this version is effective (NULL = current)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_weeks'))
    )
    op.create_table('client_contacts',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID who last changed this record (or SYSTEM_EMPLOYMENT_ID)'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_contacts_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_contacts'))
    )
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_table('documents',
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_versions.id'], name=op.f('fk_documents_current_version_id_document_versions'), use_alter=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_documents_document_type_id_document_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_document_type_id'), 'documents', ['document_type_id'], unique=False)
    op.create_table('employments',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERN', 'CONTRACTOR', 'CONSULTANT', name='employmenttype'), nullable=False),
    sa.Column('current_state', sa.Enum('ONBOARDING', 'PROBATION', 'CONFIRMED', 'SERVING_NOTICE', 'RESIGNED', 'TERMINATED', 'ALUMNI', name='employmentstate'), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID or SYSTEM_EMPLOYMENT_ID'),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_employments_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employments')),
    sa.UniqueConstraint('employee_code', name='uq_employments_employee_code')
    )
    op.create_index(op.f('ix_employments_person_id'), 'employments', ['person_id'], unique=False)
    op.create_table('holidays',
    sa.Column('holiday_calendar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('holiday_type', sa.Enum('NATIONAL', 'REGIONAL', 'OPTIONAL', 'COMPANY', name='holidaytype'), nullable=False),
    sa.Column('recurring_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['holiday_calendar_id'], ['holiday_calendars.id'], name=op.f('fk_holidays_holiday_calendar_id_holiday_calendars')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays'))
    )
    op.create_index(op.f('ix_holidays_holiday_calendar_id'), 'holidays', ['holiday_calendar_id'], unique=False)
    op.create_table('locations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('working_week_id', sa.Integer(), nullable=True),
    sa.Column('holiday_calendar_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('attendance_radius_meters', sa.Integer(), nullable=False),
    sa.Column('allowed_ip_cidrs', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('payroll_region', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year_start_month', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether this record has been archived'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Archive timestamp'),
    sa.Column('archived_by', sa.Integer(), nullable=True, comment='Employment ID who archived this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID who last changed this record (or SYSTEM_EMPLOYMENT_ID)'),
    sa.ForeignKeyConstraint(['holiday_calendar_id'], ['holiday_calendars.id'], name=op.f('fk_locations_holiday_calendar_id_holiday_calendars')),
    sa.ForeignKeyConstraint(['working_week_id'], ['working_weeks.id'], name=op.f('fk_locations_working_week_id_working_weeks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('logins',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('failed_attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_logins_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logins')),
    sa.UniqueConstraint('email', name='uq_logins_email'),
    sa.UniqueConstraint('person_id', name='uq_logins_person_id')
    )
    op.create_table('notifications',
    sa.Column('recipient_type', sa.Enum('EMPLOYMENT', 'DEPARTMENT', 'TEAM', name='notificationrecipienttype'), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('action', sa.Enum('OPEN', 'MARK_READ', 'ARCHIVE', 'DISMISS', name='notificationaction'), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ARCHIVED', name='notificationstatus'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], name=op.f('fk_notifications_template_id_notification_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('permissions',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'UNLOCK', name='action'), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_permissions_resource_id_resources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('resource_id', 'action', name='uq_permissions_resource_action')
    )
    op.create_index(op.f('ix_permissions_resource_id'), 'permissions', ['resource_id'], unique=False)
    op.create_table('sensitive_fields',
    sa.Column('field_key', sa.String(length=150), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_sensitive_fields_resource_id_resources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensitive_fields')),
    sa.UniqueConstraint('field_key', name='uq_sensitive_fields_field_key')
    )
    op.create_index(op.f('ix_sensitive_fields_resource_id'), 'sensitive_fields', ['resource_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('request_type', sa.String(length=100), nullable=False, comment='Polymorphic type e.g. LEAVE_REQUEST, ATTENDANCE_CORRECTION'),
    sa.Column('reference_id', sa.Integer(), nullable=False, comment='ID of the consumer entity'),
    sa.Column('requester_employment_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.Enum('DEPARTMENT_HEAD', 'DEPARTMENT', name='approvaltarget'), nullable=False),
    sa.Column('target_department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['requester_employment_id'], ['employments.id'], name=op.f('fk_approval_requests_requester_employment_id_employments')),
    sa.ForeignKeyConstraint(['target_department_id'], ['departments.id'], name=op.f('fk_approval_requests_target_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_reference_id'), 'approval_requests', ['reference_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_request_type'), 'approval_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_approval_requests_requester_employment_id'), 'approval_requests', ['requester_employment_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_target_department_id'), 'approval_requests', ['target_department_id'], unique=False)
    op.create_table('attendance_days',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'HOLIDAY', 'WEEK_OFF', 'ON_LEAVE', name='attendancestatus'), nullable=False),
    sa.Column('working_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_attendance_days_employment_id_employments')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_attendance_days_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_days')),
    sa.UniqueConstraint('employment_id', 'attendance_date', name='uq_attendance_days_employment_date')
    )
    op.create_index(op.f('ix_attendance_days_attendance_date'), 'attendance_days', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_days_employment_id'), 'attendance_days', ['employment_id'], unique=False)
    op.create_table('document_links',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('EMPLOYMENT', 'LEAVE_REQUEST', 'ATTENDANCE_CORRECTION', 'APPROVAL_REQUEST', 'NOTE', 'OTHER', 'LEAD', 'PROJECT', 'TASK', 'CLIENT', name='documentlinktype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_links_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_links'))
    )
    op.create_index(op.f('ix_document_links_document_id'), 'document_links', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_links_entity_id'), 'document_links', ['entity_id'], unique=False)
    op.create_index(op.f('ix_document_links_entity_type'), 'document_links', ['entity_type'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_reference', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions'))
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('employee_bank_accounts',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_employee_bank_accounts_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_bank_accounts'))
    )
    op.create_index(op.f('ix_employee_bank_accounts_employment_id'), 'employee_bank_accounts', ['employment_id'], unique=False)
    op.create_table('employee_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_employee_roles_employment_id_employments')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_employee_roles_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_roles')),
    sa.UniqueConstraint('employment_id', 'role_id', name='uq_employee_roles_employment_role')
    )
    op.create_index(op.f('ix_employee_roles_employment_id'), 'employee_roles', ['employment_id'], unique=False)
    op.create_index(op.f('ix_employee_roles_role_id'), 'employee_roles', ['role_id'], unique=False)
    op.create_table('employee_salary',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Date from which this version becomes effective'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Date until which this version is effective (NULL = current)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_employee_salary_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_salary'))
    )
    op.create_index(op.f('ix_employee_salary_employment_id'), 'employee_salary', ['employment_id'], unique=False)
    op.create_table('employment_assignments',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('work_mode', sa.Enum('OFFICE', 'WFH', name='workmode'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('change_reason', sa.String(length=100), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employment_assignments_department_id_departments')),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_employment_assignments_employment_id_employments')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_employment_assignments_location_id_locations')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_employment_assignments_position_id_positions')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_employment_assignments_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employment_assignments'))
    )
    op.create_index(op.f('ix_employment_assignments_employment_id'), 'employment_assignments', ['employment_id'], unique=False)
    op.create_table('employment_state_history',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('previous_state', sa.Enum('ONBOARDING', 'PROBATION', 'CONFIRMED', 'SERVING_NOTICE', 'RESIGNED', 'TERMINATED', 'ALUMNI', name='employmentstate'), nullable=True),
    sa.Column('new_state', sa.Enum('ONBOARDING', 'PROBATION', 'CONFIRMED', 'SERVING_NOTICE', 'RESIGNED', 'TERMINATED', 'ALUMNI', name='employmentstate'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_employment_state_history_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employment_state_history'))
    )
    op.create_index(op.f('ix_employment_state_history_employment_id'), 'employment_state_history', ['employment_id'], unique=False)
    op.create_table('leads',
    sa.Column('lead_title', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('quotation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('assigned_employment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PROPOSAL_SENT', 'CHAT_OPEN', 'MEETING', 'EXECUTION_PLAN_SENT', 'PAYMENT_DISCUSSION', 'WON', 'LOST', 'FOLLOW_UP', 'CLOSED', name='leadstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('auto_create_project', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID who last changed this record (or SYSTEM_EMPLOYMENT_ID)'),
    sa.ForeignKeyConstraint(['assigned_employment_id'], ['employments.id'], name=op.f('fk_leads_assigned_employment_id_employments')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_leads_client_id_clients')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_leads_platform_id_platforms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_assigned_employment_id'), 'leads', ['assigned_employment_id'], unique=False)
    op.create_index(op.f('ix_leads_client_id'), 'leads', ['client_id'], unique=False)
    op.create_table('leave_ledger',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'PATERNITY', 'LOSS_OF_PAY', 'COMP_OFF', name='leavetype'), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('days', sa.Numeric(precision=6, scale=2), nullable=False, comment='Positive = credit, negative = debit'),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_leave_ledger_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_ledger'))
    )
    op.create_index(op.f('ix_leave_ledger_employment_id'), 'leave_ledger', ['employment_id'], unique=False)
    op.create_index(op.f('ix_leave_ledger_leave_type'), 'leave_ledger', ['leave_type'], unique=False)
    op.create_table('monthly_attendance_summaries',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('present_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('absent_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('half_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('holiday_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('week_off_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('on_leave_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('working_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('late_count', sa.Integer(), nullable=True),
    sa.Column('early_departure_count', sa.Integer(), nullable=True),
    sa.Column('attendance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rebuilt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_monthly_attendance_summaries_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_attendance_summaries')),
    sa.UniqueConstraint('employment_id', 'year', 'month', name='uq_monthly_attendance_summaries_emp_year_month')
    )
    op.create_index(op.f('ix_monthly_attendance_summaries_employment_id'), 'monthly_attendance_summaries', ['employment_id'], unique=False)
    op.create_table('monthly_payroll',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CALCULATED', 'APPROVED', 'PAID', name='payrollstatus'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payable_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_monthly_payroll_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_payroll')),
    sa.UniqueConstraint('employment_id', 'year', 'month', name='uq_monthly_payroll_emp_year_month')
    )
    op.create_index(op.f('ix_monthly_payroll_employment_id'), 'monthly_payroll', ['employment_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_notification_preferences_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('employment_id', 'channel', name='uq_notification_preferences_employment_channel')
    )
    op.create_index(op.f('ix_notification_preferences_employment_id'), 'notification_preferences', ['employment_id'], unique=False)
    op.create_table('organization_settings',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('head_office_location_id', sa.Integer(), nullable=True),
    sa.Column('default_timezone', sa.String(length=100), nullable=False),
    sa.Column('default_currency', sa.String(length=20), nullable=False),
    sa.Column('logo_reference', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='Employment ID who last changed this record (or SYSTEM_EMPLOYMENT_ID)'),
    sa.ForeignKeyConstraint(['head_office_location_id'], ['locations.id'], name=op.f('fk_organization_settings_head_office_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_settings'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['login_id'], ['logins.id'], name=op.f('fk_password_reset_tokens_login_id_logins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_login_id'), 'password_reset_tokens', ['login_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], name=op.f('fk_role_permissions_scope_id_scopes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', 'scope_id', name='uq_role_permissions_role_perm_scope')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_scope_id'), 'role_permissions', ['scope_id'], unique=False)
    op.create_table('role_sensitive_field_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('sensitive_field_id', sa.Integer(), nullable=False),
    sa.Column('can_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_update', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_sensitive_field_permissions_role_id_roles')),
    sa.ForeignKeyConstraint(['sensitive_field_id'], ['sensitive_fields.id'], name=op.f('fk_role_sensitive_field_permissions_sensitive_field_id_sensitive_fields')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_sensitive_field_permissions')),
    sa.UniqueConstraint('role_id', 'sensitive_field_id', name='uq_role_sensitive_field_role_field')
    )
    op.create_index(op.f('ix_role_sensitive_field_permissions_role_id'), 'role_sensitive_field_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_sensitive_field_permissions_sensitive_field_id'), 'role_sensitive_field_permissions', ['sensitive_field_id'], unique=False)
    op.create_table('sessions',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.Enum('DESKTOP', 'MOBILE', 'TABLET', 'OTHER', name='devicetype'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='sessionstatus'), nullable=False),
    sa.Column('revoked_reason', sa.Enum('USER_LOGOUT', 'ADMIN_REVOKED', 'PASSWORD_CHANGED', 'ACCOUNT_SUSPENDED', 'ACCOUNT_DISABLED', 'SESSION_EXPIRED', name='sessionrevokereason'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['login_id'], ['logins.id'], name=op.f('fk_sessions_login_id_logins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_login_id'), 'sessions', ['login_id'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('team_head_employment_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['team_head_employment_id'], ['employments.id'], name=op.f('fk_teams_team_head_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('approval_actions',
    sa.Column('approval_request_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('APPROVED', 'REJECTED', 'COMMENTED', 'FORWARDED', name='approvalactiontype'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_approval_actions_approval_request_id_approval_requests')),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_approval_actions_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_actions'))
    )
    op.create_index(op.f('ix_approval_actions_approval_request_id'), 'approval_actions', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_approval_actions_employment_id'), 'approval_actions', ['employment_id'], unique=False)
    op.create_table('attendance_breaks',
    sa.Column('attendance_day_id', sa.Integer(), nullable=False),
    sa.Column('break_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('break_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['attendance_day_id'], ['attendance_days.id'], name=op.f('fk_attendance_breaks_attendance_day_id_attendance_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_breaks'))
    )
    op.create_index(op.f('ix_attendance_breaks_attendance_day_id'), 'attendance_breaks', ['attendance_day_id'], unique=False)
    op.create_table('attendance_corrections',
    sa.Column('attendance_day_id', sa.Integer(), nullable=False),
    sa.Column('requested_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approval_request_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='attendancecorrectionstatus'), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_attendance_corrections_approval_request_id_approval_requests')),
    sa.ForeignKeyConstraint(['attendance_day_id'], ['attendance_days.id'], name=op.f('fk_attendance_corrections_attendance_day_id_attendance_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_corrections'))
    )
    op.create_index(op.f('ix_attendance_corrections_approval_request_id'), 'attendance_corrections', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_attendance_day_id'), 'attendance_corrections', ['attendance_day_id'], unique=False)
    op.create_table('attendance_punches',
    sa.Column('attendance_day_id', sa.Integer(), nullable=False),
    sa.Column('punch_type', sa.Enum('CHECK_IN', 'CHECK_OUT', name='punchtype'), nullable=False),
    sa.Column('punch_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('accuracy_meters', sa.Integer(), nullable=True),
    sa.Column('client_ip', postgresql.INET(), nullable=False),
    sa.Column('is_valid_punch', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['attendance_day_id'], ['attendance_days.id'], name=op.f('fk_attendance_punches_attendance_day_id_attendance_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_punches'))
    )
    op.create_index(op.f('ix_attendance_punches_attendance_day_id'), 'attendance_punches', ['attendance_day_id'], unique=False)
    op.create_table('employee_salary_items',
    sa.Column('employee_salary_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('EARNING', 'DEDUCTION', name='salaryitemtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['employee_salary_id'], ['employee_salary.id'], name=op.f('fk_employee_salary_items_employee_salary_id_employee_salary')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_salary_items'))
    )
    op.create_index(op.f('ix_employee_salary_items_employee_salary_id'), 'employee_salary_items', ['employee_salary_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'PATERNITY', 'LOSS_OF_PAY', 'COMP_OFF', name='leavetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approval_request_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leaverequeststatus'), nullable=False),
    sa.Column('days', sa.Numeric(precision=6, scale=2), nullable=True, comment='Cached duration in days; derived at submit time'),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_leave_requests_approval_request_id_approval_requests')),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_leave_requests_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_index(op.f('ix_leave_requests_approval_request_id'), 'leave_requests', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_employment_id'), 'leave_requests', ['employment_id'], unique=False)
    op.create_table('monthly_payroll_items',
    sa.Column('monthly_payroll_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('EARNING', 'DEDUCTION', 'ADJUSTMENT', name='payrollitemtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.ForeignKeyConstraint(['monthly_payroll_id'], ['monthly_payroll.id'], name=op.f('fk_monthly_payroll_items_monthly_payroll_id_monthly_payroll')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_payroll_items'))
    )
    op.create_index(op.f('ix_monthly_payroll_items_monthly_payroll_id'), 'monthly_payroll_items', ['monthly_payroll_id'], unique=False)
    op.create_table('projects',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignment_type', sa.Enum('INDIVIDUAL', 'TEAM', name='projectassignmenttype'), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False, comment='employment_id or team_id per assignment_type'),
    sa.Column('repository_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('phase', sa.Enum('INITIAL', 'DISCOVERY', 'ANALYSIS', 'DESIGN', 'DEVELOPMENT', 'TESTING', 'UAT', 'DEPLOYMENT', 'MAINTENANCE', 'CLOSED', name='projectphase'), nullable=False),
    sa.Column('created_from', sa.Enum('LEAD', 'MANUAL', name='projectsource'), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_projects_client_id_clients')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_projects_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('lead_id', name='uq_projects_lead_id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_lead_id'), 'projects', ['lead_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('team_role', sa.String(length=100), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_team_members_employment_id_employments')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'employment_id', name='uq_team_members_team_employment')
    )
    op.create_index(op.f('ix_team_members_employment_id'), 'team_members', ['employment_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('tasks',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_employment_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETED', 'BLOCKED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commit_reference', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['assignee_employment_id'], ['employments.id'], name=op.f('fk_tasks_assignee_employment_id_employments')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_assignee_employment_id'), 'tasks', ['assignee_employment_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_table('task_time_entries',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_task_time_entries_employment_id_employments')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_time_entries_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_time_entries')),
    sa.UniqueConstraint('task_id', 'employment_id', 'work_date', name='uq_task_time_entries_task_emp_date')
    )
    op.create_index(op.f('ix_task_time_entries_employment_id'), 'task_time_entries', ['employment_id'], unique=False)
    op.create_index(op.f('ix_task_time_entries_task_id'), 'task_time_entries', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_time_entries_task_id'), table_name='task_time_entries')
    op.drop_index(op.f('ix_task_time_entries_employment_id'), table_name='task_time_entries')
    op.drop_table('task_time_entries')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_employment_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_employment_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_projects_lead_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_monthly_payroll_items_monthly_payroll_id'), table_name='monthly_payroll_items')
    op.drop_table('monthly_payroll_items')
    op.drop_index(op.f('ix_leave_requests_employment_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_approval_request_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_employee_salary_items_employee_salary_id'), table_name='employee_salary_items')
    op.drop_table('employee_salary_items')
    op.drop_index(op.f('ix_attendance_punches_attendance_day_id'), table_name='attendance_punches')
    op.drop_table('attendance_punches')
    op.drop_index(op.f('ix_attendance_corrections_attendance_day_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_approval_request_id'), table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index(op.f('ix_attendance_breaks_attendance_day_id'), table_name='attendance_breaks')
    op.drop_table('attendance_breaks')
    op.drop_index(op.f('ix_approval_actions_employment_id'), table_name='approval_actions')
    op.drop_index(op.f('ix_approval_actions_approval_request_id'), table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sessions_login_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_role_sensitive_field_permissions_sensitive_field_id'), table_name='role_sensitive_field_permissions')
    op.drop_index(op.f('ix_role_sensitive_field_permissions_role_id'), table_name='role_sensitive_field_permissions')
    op.drop_table('role_sensitive_field_permissions')
    op.drop_index(op.f('ix_role_permissions_scope_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_password_reset_tokens_login_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('organization_settings')
    op.drop_index(op.f('ix_notification_preferences_employment_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_monthly_payroll_employment_id'), table_name='monthly_payroll')
    op.drop_table('monthly_payroll')
    op.drop_index(op.f('ix_monthly_attendance_summaries_employment_id'), table_name='monthly_attendance_summaries')
    op.drop_table('monthly_attendance_summaries')
    op.drop_index(op.f('ix_leave_ledger_leave_type'), table_name='leave_ledger')
    op.drop_index(op.f('ix_leave_ledger_employment_id'), table_name='leave_ledger')
    op.drop_table('leave_ledger')
    op.drop_index(op.f('ix_leads_client_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_employment_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_employment_state_history_employment_id'), table_name='employment_state_history')
    op.drop_table('employment_state_history')
    op.drop_index(op.f('ix_employment_assignments_employment_id'), table_name='employment_assignments')
    op.drop_table('employment_assignments')
    op.drop_index(op.f('ix_employee_salary_employment_id'), table_name='employee_salary')
    op.drop_table('employee_salary')
    op.drop_index(op.f('ix_employee_roles_role_id'), table_name='employee_roles')
    op.drop_index(op.f('ix_employee_roles_employment_id'), table_name='employee_roles')
    op.drop_table('employee_roles')
    op.drop_index(op.f('ix_employee_bank_accounts_employment_id'), table_name='employee_bank_accounts')
    op.drop_table('employee_bank_accounts')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_links_entity_type'), table_name='document_links')
    op.drop_index(op.f('ix_document_links_entity_id'), table_name='document_links')
    op.drop_index(op.f('ix_document_links_document_id'), table_name='document_links')
    op.drop_table('document_links')
    op.drop_index(op.f('ix_attendance_days_employment_id'), table_name='attendance_days')
    op.drop_index(op.f('ix_attendance_days_attendance_date'), table_name='attendance_days')
    op.drop_table('attendance_days')
    op.drop_index(op.f('ix_approval_requests_target_department_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requester_employment_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_request_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_reference_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_sensitive_fields_resource_id'), table_name='sensitive_fields')
    op.drop_table('sensitive_fields')
    op.drop_index(op.f('ix_permissions_resource_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('logins')
    op.drop_table('locations')
    op.drop_index(op.f('ix_holidays_holiday_calendar_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_employments_person_id'), table_name='employments')
    op.drop_table('employments')
    op.drop_index(op.f('ix_documents_document_type_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_table('working_weeks')
    op.drop_table('shifts')
    op.drop_table('scopes')
    op.drop_table('roles')
    op.drop_table('resources')
    op.drop_table('positions')
    op.drop_table('platforms')
    op.drop_table('persons')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notes_reference_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_reference_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_leave_policies_leave_type'), table_name='leave_policies')
    op.drop_table('leave_policies')
    op.drop_table('holiday_calendars')
    op.drop_table('document_types')
    op.drop_table('departments')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_logs_reference_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_reference_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_employment_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('attendance_policies')
    # ### end Alembic commands ###
