"""add_documents_current_version_fk

Revision ID: 4b92cd0d6eb8
Revises: 4228221ecb21
Create Date: 2026-09-19 22:46:50.735106
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b92cd0d6eb8'
down_revision: Union[str, None] = '4228221ecb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_documents_current_version_id_document_versions'), 'documents', 'document_versions', ['current_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_current_version_id_document_versions'), 'documents', type_='foreignkey')
    # ### end Alembic commands ###
