"""normalize_archive_column_comments

Revision ID: cb66898874ca
Revises: f6a7b8c9d0e1
Create Date: 2026-09-20 14:47:50.832250
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb66898874ca'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logins', 'is_archived',
               existing_type=sa.BOOLEAN(),
               comment='Whether this record has been archived',
               existing_comment='Whether this login has been soft-deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('logins', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Archive timestamp',
               existing_comment='Soft-delete timestamp',
               existing_nullable=True)
    op.alter_column('logins', 'archived_by',
               existing_type=sa.INTEGER(),
               comment='Employment ID who archived this record',
               existing_comment='Employment ID who deleted this login',
               existing_nullable=True)
    op.alter_column('roles', 'is_archived',
               existing_type=sa.BOOLEAN(),
               comment='Whether this record has been archived',
               existing_comment='Whether this role has been soft-deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Archive timestamp',
               existing_comment='Soft-delete timestamp',
               existing_nullable=True)
    op.alter_column('roles', 'archived_by',
               existing_type=sa.INTEGER(),
               comment='Employment ID who archived this record',
               existing_comment='Employment ID who deleted this role',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'archived_by',
               existing_type=sa.INTEGER(),
               comment='Employment ID who deleted this role',
               existing_comment='Employment ID who archived this record',
               existing_nullable=True)
    op.alter_column('roles', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft-delete timestamp',
               existing_comment='Archive timestamp',
               existing_nullable=True)
    op.alter_column('roles', 'is_archived',
               existing_type=sa.BOOLEAN(),
               comment='Whether this role has been soft-deleted',
               existing_comment='Whether this record has been archived',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('logins', 'archived_by',
               existing_type=sa.INTEGER(),
               comment='Employment ID who deleted this login',
               existing_comment='Employment ID who archived this record',
               existing_nullable=True)
    op.alter_column('logins', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft-delete timestamp',
               existing_comment='Archive timestamp',
               existing_nullable=True)
    op.alter_column('logins', 'is_archived',
               existing_type=sa.BOOLEAN(),
               comment='Whether this login has been soft-deleted',
               existing_comment='Whether this record has been archived',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
