"""add_leads_ui_fields

Revision ID: f1c2d4b87ad6
Revises: 4b92cd0d6eb8
Create Date: 2026-09-19 22:48:43.491667
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c2d4b87ad6'
down_revision: Union[str, None] = '4b92cd0d6eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('contact_title', sa.String(length=150), nullable=True))
    op.add_column('leads', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('chat_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'chat_link')
    op.drop_column('leads', 'priority')
    op.drop_column('leads', 'contact_title')
    # ### end Alembic commands ###
