"""Leave types master + FK migration (replaces leavetype enum).

Revision ID: m3n4o5p6q7r8
"""

from __future__ import annotations

from typing import Union

from alembic import op

revision: str = "m3n4o5p6q7r8"
down_revision: Union[str, None] = "l2m3n4o5p6q7"

_SEED = [
    # (code, name, description, is_paid, requires_approval, requires_document,
    #  allow_half_day, allow_hourly, is_encashable, default_days, sort_order)
    ("CASUAL", "Casual", "Short personal leave", True, True, False, True, False, False, "12", 0),
    ("SICK", "Sick", "Leave on medical grounds", True, True, True, True, False, False, "12", 1),
    ("EARNED", "Earned", "Accrued privileged leave", True, True, False, True, False, True, "15", 2),
    ("MATERNITY", "Maternity", "Maternity leave", True, True, True, False, False, False, "182", 3),
    ("PATERNITY", "Paternity", "Paternity leave", True, True, False, False, False, False, "15", 4),
    ("LOSS_OF_PAY", "Unpaid", "Unpaid leave of absence", False, True, False, True, False, False, "0", 5),
    ("COMP_OFF", "Comp Off", "Compensatory off for extra work", True, True, False, True, False, False, "0", 6),
]

_TABLES = ("leave_policies", "leave_requests", "leave_ledger")


def _seed_sql() -> str:
    values = ",\n".join(
        "('%s','%s','%s',%s,%s,%s,%s,%s,%s,%s,%d)"
        % (
            code,
            name,
            desc,
            str(paid).lower(),
            str(appr).lower(),
            str(doc).lower(),
            str(half).lower(),
            str(hourly).lower(),
            str(encash).lower(),
            days,
            order,
        )
        for code, name, desc, paid, appr, doc, half, hourly, encash, days, order in _SEED
    )
    return (
        "INSERT INTO leave_types (code, name, description, is_paid, "
        "requires_approval, requires_document, allow_half_day, allow_hourly, "
        "is_encashable, default_annual_entitlement, sort_order) "
        f"VALUES {values} ON CONFLICT (code) DO NOTHING"
    )


def upgrade() -> None:
    op.execute(
        "CREATE TABLE IF NOT EXISTS leave_types ("
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "code VARCHAR(50) NOT NULL UNIQUE, "
        "name VARCHAR(150) NOT NULL, "
        "description TEXT NULL, "
        "is_paid BOOLEAN NOT NULL DEFAULT true, "
        "requires_approval BOOLEAN NOT NULL DEFAULT true, "
        "requires_document BOOLEAN NOT NULL DEFAULT false, "
        "allow_half_day BOOLEAN NOT NULL DEFAULT true, "
        "allow_hourly BOOLEAN NOT NULL DEFAULT false, "
        "is_encashable BOOLEAN NOT NULL DEFAULT false, "
        "default_annual_entitlement NUMERIC(6,2) NOT NULL DEFAULT 0, "
        "is_active BOOLEAN NOT NULL DEFAULT true, "
        "sort_order INTEGER NOT NULL DEFAULT 0, "
        "created_at TIMESTAMPTZ NOT NULL DEFAULT now(), "
        "updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), "
        "deleted_at TIMESTAMPTZ NULL)"
    )
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_leave_types_code ON leave_types (code)")
    op.execute(_seed_sql())

    for table in _TABLES:
        op.execute(
            f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS "
            "leave_type_id INTEGER NULL"
        )
        op.execute(
            f"UPDATE {table} SET leave_type_id = lt.id FROM leave_types lt "
            f"WHERE lt.code = {table}.leave_type::text AND {table}.leave_type_id IS NULL"
        )
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN leave_type_id SET NOT NULL"
        )
        op.execute(
            f"ALTER TABLE {table} ADD CONSTRAINT fk_{table}_leave_type "
            "FOREIGN KEY (leave_type_id) REFERENCES leave_types (id)"
        )
        op.execute(f"CREATE INDEX IF NOT EXISTS ix_{table}_leave_type_id ON {table} (leave_type_id)")
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS leave_type")
    op.execute("DROP TYPE IF EXISTS leavetype")


def downgrade() -> None:
    op.execute(
        "CREATE TYPE leavetype AS ENUM ('CASUAL','SICK','EARNED','MATERNITY',"
        "'PATERNITY','LOSS_OF_PAY','COMP_OFF')"
    )
    for table in _TABLES:
        op.execute(
            f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS leave_type leavetype NULL"
        )
        op.execute(
            f"UPDATE {table} SET leave_type = lt.code::leavetype "
            f"FROM leave_types lt WHERE lt.id = {table}.leave_type_id"
        )
        op.execute(f"ALTER TABLE {table} ALTER COLUMN leave_type SET NOT NULL")
        op.execute(
            f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS fk_{table}_leave_type"
        )
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS leave_type_id")
    op.execute("DROP TABLE IF EXISTS leave_types")
