"""User preferences table (profile settings + avatar).

Revision ID: n4o5p6q7r8s9
"""

from __future__ import annotations

from typing import Union

from alembic import op

revision: str = "n4o5p6q7r8s9"
down_revision: Union[str, None] = "m3n4o5p6q7r8"


def upgrade() -> None:
    op.execute(
        "CREATE TABLE IF NOT EXISTS user_preferences ("
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "login_id INTEGER NOT NULL UNIQUE REFERENCES logins (id), "
        "language VARCHAR(10) NOT NULL DEFAULT 'en', "
        "theme VARCHAR(20) NOT NULL DEFAULT 'system', "
        "timezone VARCHAR(64) NULL, "
        "location VARCHAR(255) NULL, "
        "avatar_object TEXT NULL, "
        "created_at TIMESTAMPTZ NOT NULL DEFAULT now(), "
        "updated_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_user_preferences_login_id "
        "ON user_preferences (login_id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS user_preferences")
